### ISSUE TITLE
bug crash

### ISSUE THREAD

**Issue by JeremyLyokoPPG2020** [thiekus/fsvwin#1]
if change color and click ok and may crashed (has stopped working) before fix

**Comment by achmadsutardi441953** [comment]
> if change color and click ok and may crashed (has stopped working) before fix

**Comment by thiekus** [comment]
Appears fsv still use problematic deprecated functions like ```gtk_object_get_data``` instead ```g_object_get_data```. I'll fix soon for next build.

Update: Color picker callback seems wrong and will be fixed.

**Comment by thiekus** [comment]
Seems solved from build 2, case closed.
