### ISSUE TITLE
file type not displayed in propeties

### ISSUE THREAD

**Issue by JeremyLyokoPPG2020** [thiekus/fsvwin#2]
Right click to propeties
![Captusdssdsre](https://user-images.githubusercontent.com/30205044/58376953-90106800-7fa0-11e9-8ad9-db05a8940397.PNG)
after displayed propeties and click "File type" on tab

and file type not displayed "This file is recognized as:" (is not displyed) is before fix

![Caasdpture](https://user-images.githubusercontent.com/30205044/58376923-d87b5600-7f9f-11e9-855b-2543dcfbb8d8.PNG)

**Comment by thiekus** [comment]
That's because file information routine still derived from unix version. I have reimplemented file type info in Windows API so it will fixed soon as next build.

**Comment by thiekus** [comment]
Implemented from build 3, case closed.
